DROP TABLE IF EXISTS births_data;
CREATE TABLE births_data AS
SELECT 
	2008 as table_year,
	"births_08"."NACIMIENTO"."CEDOCVE" as registration_state,
	"births_08"."NACIMIENTO"."ENT_NACM" as mother_birth_state,
	"births_08"."NACIMIENTO"."MPO_NACM" as mother_birth_muni,
	to_date("births_08"."NACIMIENTO"."FECH_NACM", 'DD/MM/YYYY') as mother_dob,
	"births_08"."NACIMIENTO"."EDOCIVIL"::int as mother_civil_status,
	"births_08"."NACIMIENTO"."ENT_RES" as mother_res_state,
	"births_08"."NACIMIENTO"."MPO_RES" as mother_res_muni,
	"births_08"."NACIMIENTO"."LOC_RES" as mother_res_loc,
	"births_08"."NACIMIENTO"."NUM_EMB"::int as mother_pregnancies,
	"births_08"."NACIMIENTO"."NUM_NACMTO"::int as mother_still_births,
	"births_08"."NACIMIENTO"."NUM_NACVIVO"::int as mother_live_births,
	"births_08"."NACIMIENTO"."HIJO_SOBV"::int as mother_surviving_births,
	"births_08"."NACIMIENTO"."HIJO_ANTE"::int as prev_child_status,
	"births_08"."NACIMIENTO"."VIVE_AUN"::int as prev_child_alive,
	"births_08"."NACIMIENTO"."ORDEN_NAC"::int as child_birth_order,
	"births_08"."NACIMIENTO"."ATEN_PREN"::int as mother_prenatal_care,
	"births_08"."NACIMIENTO"."TRIM_CONS"::int as first_prenatal_trimester,
	"births_08"."NACIMIENTO"."TOT_CONS"::int as total_prenatal_consultations,
	"births_08"."NACIMIENTO"."SOB_PARTO"::int as mother_survived,
	CASE
		WHEN "births_08"."NACIMIENTO"."DERHAB" = '9' THEN 99
		ELSE "births_08"."NACIMIENTO"."DERHAB"::int
	END as mother_health_affiliation,
	CASE
		WHEN "births_08"."NACIMIENTO"."DERHAB2" = '9' THEN 99
		ELSE "births_08"."NACIMIENTO"."DERHAB2"::int
	END as mother_health_affiliation2,
	CASE
		WHEN "births_08"."NACIMIENTO"."NIV_ESCOL" = '9' THEN 99
		ELSE "births_08"."NACIMIENTO"."NIV_ESCOL"::int
	END as mother_schooling,
	"births_08"."NACIMIENTO"."OCUPHAB" as mother_occupation,
	"births_08"."NACIMIENTO"."CVEOCUPHAB"::int as mother_occupation_code,
	to_date("births_08"."NACIMIENTO"."FECH_NACH", 'DD/MM/YYYY') as child_dob,
	"births_08"."NACIMIENTO"."HORA_NACH"::time as child_dob_time,
	"births_08"."NACIMIENTO"."SEXOH"::int as child_sex,
	"births_08"."NACIMIENTO"."GESTACH"::int as child_gestation_weeks,
	"births_08"."NACIMIENTO"."TALLAH"::int as child_size,
	"births_08"."NACIMIENTO"."PESOH"::int as child_weight,
	"births_08"."NACIMIENTO"."APGARH"::int as child_apgar,
	"births_08"."NACIMIENTO"."SILVERMAN"::int as child_silverman,
	"births_08"."NACIMIENTO"."BCG"::int as child_bcg_vaccine,
	"births_08"."NACIMIENTO"."PRODUCTO"::int as twins,
	"births_08"."NACIMIENTO"."ACELRN" as child_diseases,
	"births_08"."NACIMIENTO"."CVE_CIE" as child_disease_icd10,
	"births_08"."NACIMIENTO"."PROCNAC"::int as birth_procedure,
	"births_08"."NACIMIENTO"."INST_NAC"::int as place_of_birth,
	"births_08"."NACIMIENTO"."UNIMED" as medical_unit,
	"births_08"."NACIMIENTO"."CLUES" as clues_code,
	"births_08"."NACIMIENTO"."ATENDIO"::int as attending_personnel,
	"births_08"."NACIMIENTO"."ATEN_OTRO" as other_attending,
	"births_08"."NACIMIENTO"."ENT_NAC" as state_of_birth,
	"births_08"."NACIMIENTO"."MPO_NAC" as municipality_of_birth,
	"births_08"."NACIMIENTO"."LOC_NAC" as locality_of_birth,
	"births_08"."NACIMIENTO"."CERT_POR"::int as certifying_personnel,
	"births_08"."NACIMIENTO"."OTROMEDICO" as certifying_physician,
	"births_08"."NACIMIENTO"."ENT_CERT" as state_of_certification,
	"births_08"."NACIMIENTO"."MPO_CERT" as municipality_of_certification,
	"births_08"."NACIMIENTO"."LOC_CERT" as locality_of_certification,
	to_date("births_08"."NACIMIENTO"."FECH_CERT", 'DD/MM/YYYY') as certification_date,
	"births_08"."NACIMIENTO"."FECH_ALTA" as date_of_certification_expedition,
	NULL as prev_child_dob,
	NULL as mother_currently_work,
	NULL as hep_b_applied,
	NULL as vit_a_applied,
	NULL as vit_k_applied,
	NULL as met_test_applied,
	NULL as aud_test_applied,
	NULL as child_diseases2,
	NULL as child_disease2_icd10,
	NULL as certifying_med_entity,
	NULL as certifying_med_clues,
	--"births_08"."NACIMIENTO"."SABIN"::int as unknown_sabin,
	--NULL as unknown_edad_madre,
	--NULL as unknown_dias_alta_cert,
	"births_08"."NACIMIENTO"."ESPECIFIQUE" as procedure_description
FROM "births_08"."NACIMIENTO"
UNION ALL
SELECT
	2009 as table_year,
	"births_09"."NACIMIENTO"."CEDOCVE" as registration_state,
	"births_09"."NACIMIENTO"."ENT_NACM" as mother_birth_state,
	"births_09"."NACIMIENTO"."MPO_NACM" as mother_birth_muni,
	to_date("births_09"."NACIMIENTO"."FECH_NACM", 'DD/MM/YYYY') as mother_dob,
	"births_09"."NACIMIENTO"."EDOCIVIL"::int as mother_civil_status,
	"births_09"."NACIMIENTO"."ENT_RES" as mother_res_state,
	"births_09"."NACIMIENTO"."MPO_RES" as mother_res_muni,
	"births_09"."NACIMIENTO"."LOC_RES" as mother_res_loc,
	"births_09"."NACIMIENTO"."NUM_EMB"::int as mother_pregnancies,
	"births_09"."NACIMIENTO"."NUM_NACMTO"::int as mother_still_births,
	"births_09"."NACIMIENTO"."NUM_NACVIVO"::int as mother_live_births,
	"births_09"."NACIMIENTO"."HIJO_SOBV"::int as mother_surviving_births,
	"births_09"."NACIMIENTO"."HIJO_ANTE"::int as prev_child_status,
	"births_09"."NACIMIENTO"."VIVE_AUN"::int as prev_child_alive,
	"births_09"."NACIMIENTO"."ORDEN_NAC"::int as child_birth_order,
	"births_09"."NACIMIENTO"."ATEN_PREN"::int as mother_prenatal_care,
	"births_09"."NACIMIENTO"."TRIM_CONS"::int as first_prenatal_trimester,
	"births_09"."NACIMIENTO"."TOT_CONS"::int as total_prenatal_consultations,
	"births_09"."NACIMIENTO"."SOB_PARTO"::int as mother_survived,
	"births_09"."NACIMIENTO"."DERHAB"::int as mother_health_affiliation,
	"births_09"."NACIMIENTO"."DERHAB2"::int as mother_health_affiliation2,
	"births_09"."NACIMIENTO"."NIV_ESCOL"::int as mother_schooling,
	"births_09"."NACIMIENTO"."OCUPHAB" as mother_occupation,
	"births_09"."NACIMIENTO"."CVEOCUPHAB"::int as mother_occupation_code,
	to_date("births_09"."NACIMIENTO"."FECH_NACH", 'DD/MM/YYYY') as child_dob,
	"births_09"."NACIMIENTO"."HORA_NACH"::time as child_dob_time,
	"births_09"."NACIMIENTO"."SEXOH"::int as child_sex,
	"births_09"."NACIMIENTO"."GESTACH"::int as child_gestation_weeks,
	"births_09"."NACIMIENTO"."TALLAH"::int as child_size,
	"births_09"."NACIMIENTO"."PESOH"::int as child_weight,
	"births_09"."NACIMIENTO"."APGARH"::int as child_apgar,
	"births_09"."NACIMIENTO"."SILVERMAN"::int as child_silverman,
	"births_09"."NACIMIENTO"."BCG"::int as child_bcg_vaccine,
	"births_09"."NACIMIENTO"."PRODUCTO"::int as twins,
	"births_09"."NACIMIENTO"."ACELRN" as child_diseases,
	"births_09"."NACIMIENTO"."CVE_CIE" as child_disease_icd10,
	"births_09"."NACIMIENTO"."PROCNAC"::int as birth_procedure,
	"births_09"."NACIMIENTO"."INST_NAC"::int as place_of_birth,
	"births_09"."NACIMIENTO"."UNIMED" as medical_unit,
	"births_09"."NACIMIENTO"."CLUES" as clues_code,
	"births_09"."NACIMIENTO"."ATENDIO"::int as attending_personnel,
	"births_09"."NACIMIENTO"."ATEN_OTRO" as other_attending,
	"births_09"."NACIMIENTO"."ENT_NAC" as state_of_birth,
	"births_09"."NACIMIENTO"."MPO_NAC" as municipality_of_birth,
	"births_09"."NACIMIENTO"."LOC_NAC" as locality_of_birth,
	"births_09"."NACIMIENTO"."CERT_POR"::int as certifying_personnel,
	"births_09"."NACIMIENTO"."OTROMEDICO" as certifying_physician,
	"births_09"."NACIMIENTO"."ENT_CERT" as state_of_certification,
	"births_09"."NACIMIENTO"."MPO_CERT" as municipality_of_certification,
	"births_09"."NACIMIENTO"."LOC_CERT" as locality_of_certification,
	to_date("births_09"."NACIMIENTO"."FECH_CERT", 'DD/MM/YYYY') as certification_date,
	"births_09"."NACIMIENTO"."FECH_ALTA" as date_of_certification_expedition,
	CASE
		WHEN "births_09"."NACIMIENTO"."FECH_NHEA" = '__/__/____' THEN NULL
		ELSE to_date("births_09"."NACIMIENTO"."FECH_NHEA", 'DD/MM/YYYY')
	END as prev_child_dob,
	"births_09"."NACIMIENTO"."TRAB_ACT"::int as mother_currently_work,
	"births_09"."NACIMIENTO"."HEP_B"::int as hep_b_applied,
	"births_09"."NACIMIENTO"."VIT_A"::int as vit_a_applied,
	"births_09"."NACIMIENTO"."VIT_K"::int as vit_k_applied,
	"births_09"."NACIMIENTO"."TAM_MET"::int as met_test_applied,
	"births_09"."NACIMIENTO"."TAM_AUD"::int as aud_test_applied,
	"births_09"."NACIMIENTO"."ACELRN2" as child_diseases2,
	"births_09"."NACIMIENTO"."CVE_CIE2" as child_disease2_icd10,
	"births_09"."NACIMIENTO"."UNIMED_33_1" as certifying_med_entity,
	"births_09"."NACIMIENTO"."CLUES_33_2" as certifying_med_clues,
	--NULL as unknown_sabin,
	--NULL as unknown_edad_madre,
	--NULL as unknown_dias_alta_cert,
	"births_09"."NACIMIENTO"."ESPECIFIQUE" as procedure_description
FROM "births_09"."NACIMIENTO"
UNION ALL
SELECT 
	2010 as table_year,
	"births_10"."NACIMIENTO"."CEDOCVE" as registration_state,
	"births_10"."NACIMIENTO"."ENT_NACM" as mother_birth_state,
	"births_10"."NACIMIENTO"."MPO_NACM" as mother_birth_muni,
	to_date("births_10"."NACIMIENTO"."FECH_NACM", 'DD/MM/YYYY') as mother_dob,
	"births_10"."NACIMIENTO"."EDOCIVIL"::int as mother_civil_status,
	"births_10"."NACIMIENTO"."ENT_RES" as mother_res_state,
	"births_10"."NACIMIENTO"."MPO_RES" as mother_res_muni,
	"births_10"."NACIMIENTO"."LOC_RES" as mother_res_loc,
	"births_10"."NACIMIENTO"."NUM_EMB"::int as mother_pregnancies,
	"births_10"."NACIMIENTO"."NUM_NACMTO"::int as mother_still_births,
	"births_10"."NACIMIENTO"."NUM_NACVIVO"::int as mother_live_births,
	"births_10"."NACIMIENTO"."HIJO_SOBV"::int as mother_surviving_births,
	"births_10"."NACIMIENTO"."HIJO_ANTE"::int as prev_child_status,
	"births_10"."NACIMIENTO"."VIVE_AUN"::int as prev_child_alive,
	"births_10"."NACIMIENTO"."ORDEN_NAC"::int as child_birth_order,
	"births_10"."NACIMIENTO"."ATEN_PREN"::int as mother_prenatal_care,
	"births_10"."NACIMIENTO"."TRIM_CONS"::int as first_prenatal_trimester,
	"births_10"."NACIMIENTO"."TOT_CONS"::int as total_prenatal_consultations,
	"births_10"."NACIMIENTO"."SOB_PARTO"::int as mother_survived,
	"births_10"."NACIMIENTO"."DERHAB"::int as mother_health_affiliation,
	"births_10"."NACIMIENTO"."DERHAB2"::int as mother_health_affiliation2,
	"births_10"."NACIMIENTO"."NIV_ESCOL"::int as mother_schooling,
	"births_10"."NACIMIENTO"."OCUPHAB" as mother_occupation,
	"births_10"."NACIMIENTO"."CVEOCUPHAB"::int as mother_occupation_code,
	to_date("births_10"."NACIMIENTO"."FECH_NACH", 'DD/MM/YYYY') as child_dob,
	"births_10"."NACIMIENTO"."HORA_NACH"::time as child_dob_time,
	"births_10"."NACIMIENTO"."SEXOH"::int as child_sex,
	"births_10"."NACIMIENTO"."GESTACH"::int as child_gestation_weeks,
	"births_10"."NACIMIENTO"."TALLAH"::int as child_size,
	"births_10"."NACIMIENTO"."PESOH"::int as child_weight,
	"births_10"."NACIMIENTO"."APGARH"::int as child_apgar,
	"births_10"."NACIMIENTO"."SILVERMAN"::int as child_silverman,
	"births_10"."NACIMIENTO"."BCG"::int as child_bcg_vaccine,
	"births_10"."NACIMIENTO"."PRODUCTO"::int as twins,
	"births_10"."NACIMIENTO"."ACELRN" as child_diseases,
	"births_10"."NACIMIENTO"."CVE_CIE" as child_disease_icd10,
	"births_10"."NACIMIENTO"."PROCNAC"::int as birth_procedure,
	"births_10"."NACIMIENTO"."INST_NAC"::int as place_of_birth,
	"births_10"."NACIMIENTO"."UNIMED" as medical_unit,
	"births_10"."NACIMIENTO"."CLUES" as clues_code,
	"births_10"."NACIMIENTO"."ATENDIO"::int as attending_personnel,
	"births_10"."NACIMIENTO"."ATEN_OTRO" as other_attending,
	"births_10"."NACIMIENTO"."ENT_NAC" as state_of_birth,
	"births_10"."NACIMIENTO"."MPO_NAC" as municipality_of_birth,
	"births_10"."NACIMIENTO"."LOC_NAC" as locality_of_birth,
	"births_10"."NACIMIENTO"."CERT_POR"::int as certifying_personnel,
	"births_10"."NACIMIENTO"."OTROMEDICO" as certifying_physician,
	"births_10"."NACIMIENTO"."ENT_CERT" as state_of_certification,
	"births_10"."NACIMIENTO"."MPO_CERT" as municipality_of_certification,
	"births_10"."NACIMIENTO"."LOC_CERT" as locality_of_certification,
	to_date("births_10"."NACIMIENTO"."FECH_CERT",'DD/MM/YYYY') as certification_date,
	"births_10"."NACIMIENTO"."FECH_ALTA" as date_of_certification_expedition,
	CASE
		WHEN "births_10"."NACIMIENTO"."FECH_NHEA" = '__/__/____' THEN NULL
		ELSE to_date("births_10"."NACIMIENTO"."FECH_NHEA", 'DD/MM/YYYY')
	END as prev_child_dob,
	"births_10"."NACIMIENTO"."TRAB_ACT"::int as mother_currently_work,
	"births_10"."NACIMIENTO"."HEP_B"::int as hep_b_applied,
	"births_10"."NACIMIENTO"."VIT_A"::int as vit_a_applied,
	"births_10"."NACIMIENTO"."VIT_K"::int as vit_k_applied,
	"births_10"."NACIMIENTO"."TAM_MET"::int as met_test_applied,
	"births_10"."NACIMIENTO"."TAM_AUD"::int as aud_test_applied,
	"births_10"."NACIMIENTO"."ACELRN2" as child_diseases2,
	"births_10"."NACIMIENTO"."CVE_CIE2" as child_disease2_icd10,
	"births_10"."NACIMIENTO"."UNIMED_33_1" as certifying_med_entity,
	"births_10"."NACIMIENTO"."CLUES_33_2" as certifying_med_clues,
	--NULL as unknown_sabin,
	--NULL as unknown_edad_madre,
	--NULL as unknown_dias_alta_cert,
	"births_10"."NACIMIENTO"."ESPECIFIQUE" as procedure_description
FROM "births_10"."NACIMIENTO"
UNION ALL
SELECT
	2011 as table_year,
	"births_11"."NACIMIENTO"."CEDOCVE" as registration_state,
	"births_11"."NACIMIENTO"."ENT_NACM" as mother_birth_state,
	"births_11"."NACIMIENTO"."MPO_NACM" as mother_birth_muni,
	to_date("births_11"."NACIMIENTO"."FECH_NACM", 'DD/MM/YYYY') as mother_dob,
	"births_11"."NACIMIENTO"."EDOCIVIL"::int as mother_civil_status,
	"births_11"."NACIMIENTO"."ENT_RES" as mother_res_state,
	"births_11"."NACIMIENTO"."MPO_RES" as mother_res_muni,
	"births_11"."NACIMIENTO"."LOC_RES" as mother_res_loc,
	"births_11"."NACIMIENTO"."NUM_EMB"::int as mother_pregnancies,
	"births_11"."NACIMIENTO"."NUM_NACMTO"::int as mother_still_births,
	"births_11"."NACIMIENTO"."NUM_NACVIVO"::int as mother_live_births,
	"births_11"."NACIMIENTO"."HIJO_SOBV"::int as mother_surviving_births,
	"births_11"."NACIMIENTO"."HIJO_ANTE"::int as prev_child_status,
	"births_11"."NACIMIENTO"."VIVE_AUN"::int as prev_child_alive,
	"births_11"."NACIMIENTO"."ORDEN_NAC"::int as child_birth_order,
	"births_11"."NACIMIENTO"."ATEN_PREN"::int as mother_prenatal_care,
	"births_11"."NACIMIENTO"."TRIM_CONS"::int as first_prenatal_trimester,
	"births_11"."NACIMIENTO"."TOT_CONS"::int as total_prenatal_consultations,
	"births_11"."NACIMIENTO"."SOB_PARTO"::int as mother_survived,
	"births_11"."NACIMIENTO"."DERHAB"::int as mother_health_affiliation,
	"births_11"."NACIMIENTO"."DERHAB2"::int as mother_health_affiliation2,
	"births_11"."NACIMIENTO"."NIV_ESCOL"::int as mother_schooling,
	"births_11"."NACIMIENTO"."OCUPHAB" as mother_occupation,
	"births_11"."NACIMIENTO"."CVEOCUPHAB"::int as mother_occupation_code,
	to_date("births_11"."NACIMIENTO"."FECH_NACH", 'DD/MM/YYYY') as child_dob,
	"births_11"."NACIMIENTO"."HORA_NACH"::time as child_dob_time,
	"births_11"."NACIMIENTO"."SEXOH"::int as child_sex,
	"births_11"."NACIMIENTO"."GESTACH"::int as child_gestation_weeks,
	"births_11"."NACIMIENTO"."TALLAH"::int as child_size,
	"births_11"."NACIMIENTO"."PESOH"::int as child_weight,
	"births_11"."NACIMIENTO"."APGARH"::int as child_apgar,
	"births_11"."NACIMIENTO"."SILVERMAN"::int as child_silverman,
	"births_11"."NACIMIENTO"."BCG"::int as child_bcg_vaccine,
	"births_11"."NACIMIENTO"."PRODUCTO"::int as twins,
	"births_11"."NACIMIENTO"."ACELRN" as child_diseases,
	"births_11"."NACIMIENTO"."CVE_CIE" as child_disease_icd10,
	"births_11"."NACIMIENTO"."PROCNAC"::int as birth_procedure,
	"births_11"."NACIMIENTO"."INST_NAC"::int as place_of_birth,
	"births_11"."NACIMIENTO"."UNIMED" as medical_unit,
	"births_11"."NACIMIENTO"."CLUES" as clues_code,
	"births_11"."NACIMIENTO"."ATENDIO"::int as attending_personnel,
	"births_11"."NACIMIENTO"."ATEN_OTRO" as other_attending,
	"births_11"."NACIMIENTO"."ENT_NAC" as state_of_birth,
	"births_11"."NACIMIENTO"."MPO_NAC" as municipality_of_birth,
	"births_11"."NACIMIENTO"."LOC_NAC" as locality_of_birth,
	"births_11"."NACIMIENTO"."CERT_POR"::int as certifying_personnel,
	"births_11"."NACIMIENTO"."OTROMEDICO" as certifying_physician,
	"births_11"."NACIMIENTO"."ENT_CERT" as state_of_certification,
	"births_11"."NACIMIENTO"."MPO_CERT" as municipality_of_certification,
	"births_11"."NACIMIENTO"."LOC_CERT" as locality_of_certification,
	to_date("births_11"."NACIMIENTO"."FECH_CERT", 'DD/MM/YYYY') as certification_date,
	"births_11"."NACIMIENTO"."FECH_ALTA" as date_of_certification_expedition,
	CASE
		WHEN "births_11"."NACIMIENTO"."FECH_NHEA" = '__/__/____' THEN NULL
		ELSE to_date("births_11"."NACIMIENTO"."FECH_NHEA", 'DD/MM/YYYY')
	END as prev_child_dob,
	"births_11"."NACIMIENTO"."TRAB_ACT"::int as mother_currently_work,
	"births_11"."NACIMIENTO"."HEP_B"::int as hep_b_applied,
	"births_11"."NACIMIENTO"."VIT_A"::int as vit_a_applied,
	"births_11"."NACIMIENTO"."VIT_K"::int as vit_k_applied,
	"births_11"."NACIMIENTO"."TAM_MET"::int as met_test_applied,
	"births_11"."NACIMIENTO"."TAM_AUD"::int as aud_test_applied,
	"births_11"."NACIMIENTO"."ACELRN2" as child_diseases2,
	"births_11"."NACIMIENTO"."CVE_CIE2" as child_disease2_icd10,
	"births_11"."NACIMIENTO"."UNIMED_33_1" as certifying_med_entity,
	"births_11"."NACIMIENTO"."CLUES_33_2" as certifying_med_clues,
	--NULL as unknown_sabin,
	--NULL as unknown_edad_madre,
	--NULL as unknown_dias_alta_cert,
	"births_11"."NACIMIENTO"."ESPECIFIQUE" as procedure_description
FROM "births_11"."NACIMIENTO"
UNION ALL
SELECT
	2012 as table_year,
	"births_12"."NACIMIENTO"."CEDOCVE" as registration_state,
	"births_12"."NACIMIENTO"."ENT_NACM" as mother_birth_state,
	"births_12"."NACIMIENTO"."MPO_NACM" as mother_birth_muni,
	to_date("births_12"."NACIMIENTO"."FECH_NACM", 'DD/MM/YYYY') as mother_dob,
	"births_12"."NACIMIENTO"."EDOCIVIL"::int as mother_civil_status,
	"births_12"."NACIMIENTO"."ENT_RES" as mother_res_state,
	"births_12"."NACIMIENTO"."MPO_RES" as mother_res_muni,
	"births_12"."NACIMIENTO"."LOC_RES" as mother_res_loc,
	"births_12"."NACIMIENTO"."NUM_EMB"::int as mother_pregnancies,
	"births_12"."NACIMIENTO"."NUM_NACMTO"::int as mother_still_births,
	"births_12"."NACIMIENTO"."NUM_NACVIVO"::int as mother_live_births,
	"births_12"."NACIMIENTO"."HIJO_SOBV"::int as mother_surviving_births,
	"births_12"."NACIMIENTO"."HIJO_ANTE"::int as prev_child_status,
	"births_12"."NACIMIENTO"."VIVE_AUN"::int as prev_child_alive,
	"births_12"."NACIMIENTO"."ORDEN_NAC"::int as child_birth_order,
	"births_12"."NACIMIENTO"."ATEN_PREN"::int as mother_prenatal_care,
	"births_12"."NACIMIENTO"."TRIM_CONS"::int as first_prenatal_trimester,
	"births_12"."NACIMIENTO"."TOT_CONS"::int as total_prenatal_consultations,
	"births_12"."NACIMIENTO"."SOB_PARTO"::int as mother_survived,
	"births_12"."NACIMIENTO"."DERHAB"::int as mother_health_affiliation,
	"births_12"."NACIMIENTO"."DERHAB2"::int as mother_health_affiliation2,
	"births_12"."NACIMIENTO"."NIV_ESCOL"::int as mother_schooling,
	"births_12"."NACIMIENTO"."OCUPHAB" as mother_occupation,
	"births_12"."NACIMIENTO"."CVEOCUPHAB"::int as mother_occupation_code,
	to_date("births_12"."NACIMIENTO"."FECH_NACH", 'DD/MM/YYYY') as child_dob,
	"births_12"."NACIMIENTO"."HORA_NACH"::time as child_dob_time,
	"births_12"."NACIMIENTO"."SEXOH"::int as child_sex,
	"births_12"."NACIMIENTO"."GESTACH"::int as child_gestation_weeks,
	"births_12"."NACIMIENTO"."TALLAH"::int as child_size,
	"births_12"."NACIMIENTO"."PESOH"::int as child_weight,
	"births_12"."NACIMIENTO"."APGARH"::int as child_apgar,
	"births_12"."NACIMIENTO"."SILVERMAN"::int as child_silverman,
	"births_12"."NACIMIENTO"."BCG"::int as child_bcg_vaccine,
	"births_12"."NACIMIENTO"."PRODUCTO"::int as twins,
	"births_12"."NACIMIENTO"."ACELRN" as child_diseases,
	"births_12"."NACIMIENTO"."CVE_CIE" as child_disease_icd10,
	"births_12"."NACIMIENTO"."PROCNAC"::int as birth_procedure,
	"births_12"."NACIMIENTO"."INST_NAC"::int as place_of_birth,
	"births_12"."NACIMIENTO"."UNIMED" as medical_unit,
	"births_12"."NACIMIENTO"."CLUES" as clues_code,
	"births_12"."NACIMIENTO"."ATENDIO"::int as attending_personnel,
	"births_12"."NACIMIENTO"."ATEN_OTRO" as other_attending,
	"births_12"."NACIMIENTO"."ENT_NAC" as state_of_birth,
	"births_12"."NACIMIENTO"."MPO_NAC" as municipality_of_birth,
	"births_12"."NACIMIENTO"."LOC_NAC" as locality_of_birth,
	"births_12"."NACIMIENTO"."CERT_POR"::int as certifying_personnel,
	"births_12"."NACIMIENTO"."OTROMEDICO" as certifying_physician,
	"births_12"."NACIMIENTO"."ENT_CERT" as state_of_certification,
	"births_12"."NACIMIENTO"."MPO_CERT" as municipality_of_certification,
	"births_12"."NACIMIENTO"."LOC_CERT" as locality_of_certification,
	to_date("births_12"."NACIMIENTO"."FECH_CERT", 'DD/MM/YYYY') as certification_date,
	"births_12"."NACIMIENTO"."FECH_ALTA" as date_of_certification_expedition,
	NULL as prev_child_dob,
	"births_12"."NACIMIENTO"."TRAB_ACT"::int as mother_currently_work,
	"births_12"."NACIMIENTO"."HEP_B"::int as hep_b_applied,
	"births_12"."NACIMIENTO"."VIT_A"::int as vit_a_applied,
	"births_12"."NACIMIENTO"."VIT_K"::int as vit_k_applied,
	"births_12"."NACIMIENTO"."TAM_MET"::int as met_test_applied,
	"births_12"."NACIMIENTO"."TAM_AUD"::int as aud_test_applied,
	NULL as child_diseases2,
	NULL as child_disease2_icd10,
	NULL as certifying_med_entity,
	NULL as certifying_med_clues,
	--NULL as unknown_sabin,
	--"births_12"."NACIMIENTO"."EDAD_MADRE" as unknown_edad_madre,
	--"births_12"."NACIMIENTO"."DIAS_ALTA_CERT" as unknown_dias_alta_cert,
	NULL as procedure_description
FROM "births_12"."NACIMIENTO"
UNION ALL
SELECT
	2013 as table_year,
	"births_13"."NACIMIENTO"."CEDOCVE" as registration_state,
	"births_13"."NACIMIENTO"."ENT_NACM" as mother_birth_state,
	"births_13"."NACIMIENTO"."MPO_NACM" as mother_birth_muni,
	to_date("births_13"."NACIMIENTO"."FECH_NACM", 'DD/MM/YYYY') as mother_dob,
	"births_13"."NACIMIENTO"."EDOCIVIL"::int as mother_civil_status,
	"births_13"."NACIMIENTO"."ENT_RES" as mother_res_state,
	"births_13"."NACIMIENTO"."MPO_RES" as mother_res_muni,
	"births_13"."NACIMIENTO"."LOC_RES" as mother_res_loc,
	"births_13"."NACIMIENTO"."NUM_EMB"::int as mother_pregnancies,
	"births_13"."NACIMIENTO"."NUM_NACMTO"::int as mother_still_births,
	"births_13"."NACIMIENTO"."NUM_NACVIVO"::int as mother_live_births,
	"births_13"."NACIMIENTO"."HIJO_SOBV"::int as mother_surviving_births,
	"births_13"."NACIMIENTO"."HIJO_ANTE"::int as prev_child_status,
	"births_13"."NACIMIENTO"."VIVE_AUN"::int as prev_child_alive,
	"births_13"."NACIMIENTO"."ORDEN_NAC"::int as child_birth_order,
	"births_13"."NACIMIENTO"."ATEN_PREN"::int as mother_prenatal_care,
	"births_13"."NACIMIENTO"."TRIM_CONS"::int as first_prenatal_trimester,
	"births_13"."NACIMIENTO"."TOT_CONS"::int as total_prenatal_consultations,
	"births_13"."NACIMIENTO"."SOB_PARTO"::int as mother_survived,
	"births_13"."NACIMIENTO"."DERHAB"::int as mother_health_affiliation,
	"births_13"."NACIMIENTO"."DERHAB2"::int as mother_health_affiliation2,
	"births_13"."NACIMIENTO"."NIV_ESCOL"::int as mother_schooling,
	"births_13"."NACIMIENTO"."OCUPHAB" as mother_occupation,
	"births_13"."NACIMIENTO"."CVEOCUPHAB"::int as mother_occupation_code,
	to_date("births_13"."NACIMIENTO"."FECH_NACH", 'DD/MM/YYYY') as child_dob,
	"births_13"."NACIMIENTO"."HORA_NACH"::time as child_dob_time,
	"births_13"."NACIMIENTO"."SEXOH"::int as child_sex,
	"births_13"."NACIMIENTO"."GESTACH"::int as child_gestation_weeks,
	"births_13"."NACIMIENTO"."TALLAH"::int as child_size,
	"births_13"."NACIMIENTO"."PESOH"::int as child_weight,
	"births_13"."NACIMIENTO"."APGARH"::int as child_apgar,
	"births_13"."NACIMIENTO"."SILVERMAN"::int as child_silverman,
	"births_13"."NACIMIENTO"."BCG"::int as child_bcg_vaccine,
	"births_13"."NACIMIENTO"."PRODUCTO"::int as twins,
	"births_13"."NACIMIENTO"."ACELRN" as child_diseases,
	"births_13"."NACIMIENTO"."CVE_CIE" as child_disease_icd10,
	"births_13"."NACIMIENTO"."PROCNAC"::int as birth_procedure,
	"births_13"."NACIMIENTO"."INST_NAC"::int as place_of_birth,
	"births_13"."NACIMIENTO"."UNIMED" as medical_unit,
	"births_13"."NACIMIENTO"."CLUES" as clues_code,
	"births_13"."NACIMIENTO"."ATENDIO"::int as attending_personnel,
	"births_13"."NACIMIENTO"."ATEN_OTRO" as other_attending,
	"births_13"."NACIMIENTO"."ENT_NAC" as state_of_birth,
	"births_13"."NACIMIENTO"."MPO_NAC" as municipality_of_birth,
	"births_13"."NACIMIENTO"."LOC_NAC" as locality_of_birth,
	"births_13"."NACIMIENTO"."CERT_POR"::int as certifying_personnel,
	"births_13"."NACIMIENTO"."OTROMEDICO" as certifying_physician,
	"births_13"."NACIMIENTO"."ENT_CERT" as state_of_certification,
	"births_13"."NACIMIENTO"."MPO_CERT" as municipality_of_certification,
	"births_13"."NACIMIENTO"."LOC_CERT" as locality_of_certification,
	to_date("births_13"."NACIMIENTO"."FECH_CERT", 'DD/MM/YYYY') as certification_date,
	"births_13"."NACIMIENTO"."FECH_ALTA" as date_of_certification_expedition,
	NULL as prev_child_dob,
	"births_13"."NACIMIENTO"."TRAB_ACT"::int as mother_currently_work,
	"births_13"."NACIMIENTO"."HEP_B"::int as hep_b_applied,
	"births_13"."NACIMIENTO"."VIT_A"::int as vit_a_applied,
	"births_13"."NACIMIENTO"."VIT_K"::int as vit_k_applied,
	"births_13"."NACIMIENTO"."TAM_MET"::int as met_test_applied,
	"births_13"."NACIMIENTO"."TAM_AUD"::int as aud_test_applied,
	NULL as child_diseases2,
	NULL as child_disease2_icd10,
	NULL as certifying_med_entity,
	NULL as certifying_med_clues,
	--NULL as unknown_sabin,
	--"births_13"."NACIMIENTO"."EDAD_MADRE" as unknown_edad_madre,
	--"births_13"."NACIMIENTO"."DIAS_ALTA_CERT" as unknown_dias_alta_cert,
	NULL as procedure_description
FROM "births_13"."NACIMIENTO"
;

CREATE INDEX births_mother_res_idx on births_data (mother_res_state, mother_res_muni, mother_res_loc);

ALTER TABLE births_data
ADD COLUMN primary_key SERIAL PRIMARY KEY
;

UPDATE births_data
SET 
	certification_date = CASE WHEN certification_date IN ('0011-11-18', '0011-11-30', '0011-12-02', '0011-12-03', '0011-12-04', '0011-12-05', '0011-12-11', '0011-12-12', '0011-12-13', '0011-12-14', '0011-12-15', '0011-12-16', '0011-12-17', '0011-12-18', '0011-12-19') THEN NULL ELSE certification_date END,
	child_birth_order = CASE WHEN child_birth_order = 99 THEN NULL ELSE child_birth_order END,
	child_disease2_icd10 = CASE WHEN child_disease2_icd10 = '000' THEN '0000' ELSE child_disease2_icd10 END,
	child_gestation_weeks = CASE WHEN child_gestation_weeks = 99 THEN NULL ELSE child_gestation_weeks END,
	child_size = CASE WHEN child_size = 99 THEN NULL ELSE child_size END,
	child_weight = CASE WHEN child_weight = 9999 THEN NULL ELSE child_weight END,
	locality_of_birth = CASE WHEN locality_of_birth = '9999' THEN '0000' ELSE locality_of_birth END,
	locality_of_certification = CASE WHEN locality_of_certification = '9999' THEN '0000' ELSE locality_of_certification END,
	mother_birth_muni = CASE WHEN mother_birth_muni = '9999' THEN '0000' ELSE mother_birth_muni END,
	mother_birth_state = CASE WHEN mother_birth_state = '99' THEN '00' ELSE mother_birth_state END,
	mother_live_births = CASE WHEN mother_live_births = '99' THEN NULL ELSE mother_live_births END,
	mother_pregnancies = CASE WHEN mother_pregnancies = '99' THEN NULL ELSE mother_pregnancies END,
	mother_res_loc = CASE WHEN mother_res_loc = '9999' THEN '0000' ELSE mother_res_loc END,
	mother_res_muni = CASE WHEN mother_res_muni = '999' THEN '000' ELSE mother_res_muni END,
	mother_res_state = CASE WHEN mother_res_state = '99' THEN '00' ELSE mother_res_state END,
	mother_still_births = CASE WHEN mother_still_births = 99 THEN NULL ELSE mother_still_births END,
	mother_surviving_births = CASE WHEN mother_surviving_births = 99 THEN NULL ELSE mother_surviving_births END,
	municipality_of_birth = CASE WHEN municipality_of_birth = '999' THEN '000' ELSE municipality_of_birth END,
	municipality_of_certification = CASE WHEN municipality_of_certification = '999' THEN '000' ELSE municipality_of_certification END,
	state_of_birth = CASE WHEN state_of_birth = '99' THEN NULL ELSE state_of_birth END,
	state_of_certification = CASE WHEN state_of_certification = '99' THEN NULL ELSE state_of_certification END,
	total_prenatal_consultations = CASE WHEN total_prenatal_consultations = 99 THEN NULL ELSE total_prenatal_consultations END
	mother_dob = CASE WHEN mother_dob IN('0001-01-03','0001-02-20','0001-04-10','0001-04-18','0001-04-26','0001-04-30','0001-05-12','0001-06-10','0001-07-06','0001-07-08','0001-09-22','0001-09-27','0080-12-20','0081-08-21','0085-02-15','0091-06-27','0094-05-12','1901-05-19', '10007-06-23') THEN NULL ELSE mother_dob END,
	prev_child_dob = CASE WHEN prev_child_dob IN('0001-01-02','0001-02-14','0001-02-17','0001-10-22','0001-01-01','0001-02-01','0002-07-24','0002-11-09','0004-02-06','0004-02-08','0006-12-30','0008-02-01','0008-04-22','0009-02-26','0010-02-21','0020-02-23','0020-09-17','0020-09-24','0200-08-16','0200-09-15','0200-12-10','1005-04-23','1005-10-29','1006-12-02','1111-11-11','1899-12-30','1900-01-02','1/1/2070','3/10/8546','10007-06-23') THEN NULL ELSE prev_child_dob END
;
	
	